import { TaskPriority, TaskStatus } from '@prisma/client'
import type { SectionKey } from './meta.data'

export type AssigneeRef = number | 'owner' | null

export type SeedTask = {
  key: string
  title: string
  description?: string
  status: TaskStatus
  priority: TaskPriority
  /** Index into DEMO_TEAM_EMAILS; 'owner' = demo owner; null = unassigned */
  assigneeIndex: AssigneeRef
  sectionKey: SectionKey
  /**
   * Legacy relative hints — ignored at seed time.
   * `schedule.ts` places open work from tomorrow through a 90-day deadline.
   */
  dueInDays?: number
  startInDays?: number
  parentKey?: string
}

/**
 * Parent tasks + subtasks for the Product launch board.
 * assigneeIndex maps to DEMO_TEAM_EMAILS; 'owner' = demo owner; null = unassigned.
 */
export const DEMO_TASKS: SeedTask[] = [
  // —— TODO / GTM ——
  {
    key: 'announce-copy',
    title: 'Draft launch announcement copy',
    status: 'TODO',
    priority: 'HIGH',
    assigneeIndex: 0,
    sectionKey: 'gtm',
    dueInDays: 8,
    startInDays: 0,
  },
  {
    key: 'hero-banners',
    title: 'Design hero banner variants',
    status: 'TODO',
    priority: 'MEDIUM',
    assigneeIndex: 1,
    sectionKey: 'design',
    dueInDays: 13,
    startInDays: 3,
  },
  {
    key: 'onboarding-emails',
    title: 'Write onboarding email sequence',
    status: 'TODO',
    priority: 'HIGH',
    assigneeIndex: 2,
    sectionKey: 'gtm',
    dueInDays: 10,
    startInDays: 0,
  },
  {
    key: 'sales-onepager',
    title: 'Prepare sales one-pager PDF',
    status: 'TODO',
    priority: 'MEDIUM',
    assigneeIndex: 3,
    sectionKey: 'gtm',
    dueInDays: 18,
  },
  {
    key: 'testimonials',
    title: 'Collect customer testimonials',
    status: 'TODO',
    priority: 'LOW',
    assigneeIndex: 4,
    sectionKey: 'gtm',
    dueInDays: 25,
  },
  {
    key: 'pricing-faq',
    title: 'Update pricing page FAQ',
    status: 'TODO',
    priority: 'MEDIUM',
    assigneeIndex: 5,
    sectionKey: 'gtm',
    dueInDays: 15,
  },
  {
    key: 'influencer-outreach',
    title: 'Schedule influencer outreach',
    status: 'TODO',
    priority: 'LOW',
    assigneeIndex: null,
    sectionKey: 'gtm',
    dueInDays: 30,
  },
  {
    key: 'analytics-audit',
    title: 'Audit analytics events for launch',
    status: 'TODO',
    priority: 'HIGH',
    assigneeIndex: 0,
    sectionKey: 'engineering',
    dueInDays: 5,
    startInDays: -3,
  },
  {
    key: 'support-macros',
    title: 'Create support macro templates',
    status: 'TODO',
    priority: 'MEDIUM',
    assigneeIndex: 1,
    sectionKey: 'launch-ops',
    dueInDays: 20,
  },
  {
    key: 'legal-disclaimer',
    title: 'Review legal disclaimer text',
    status: 'TODO',
    priority: 'HIGH',
    assigneeIndex: 'owner',
    sectionKey: 'launch-ops',
    dueInDays: 8,
  },
  {
    key: 'press-kit',
    title: 'Build press kit folder',
    status: 'TODO',
    priority: 'LOW',
    assigneeIndex: 2,
    sectionKey: 'gtm',
    dueInDays: 30,
  },
  {
    key: 'affiliate-links',
    title: 'Set up affiliate tracking links',
    status: 'TODO',
    priority: 'MEDIUM',
    assigneeIndex: 3,
    sectionKey: 'gtm',
    dueInDays: 23,
  },
  {
    key: 'localize-es',
    title: 'Localize landing page (ES)',
    status: 'TODO',
    priority: 'MEDIUM',
    assigneeIndex: 4,
    sectionKey: 'gtm',
    dueInDays: 28,
  },
  {
    key: 'localize-fr',
    title: 'Localize landing page (FR)',
    status: 'TODO',
    priority: 'MEDIUM',
    assigneeIndex: 5,
    sectionKey: 'gtm',
    dueInDays: 28,
  },
  {
    key: 'webinar-deck',
    title: 'Prep webinar slide deck',
    status: 'TODO',
    priority: 'HIGH',
    assigneeIndex: 0,
    sectionKey: 'gtm',
    dueInDays: 13,
    startInDays: 3,
  },
  {
    key: 'demo-studio',
    title: 'Book demo recording studio',
    status: 'TODO',
    priority: 'LOW',
    assigneeIndex: null,
    sectionKey: 'launch-ops',
    dueInDays: 30,
  },
  {
    key: 'changelog',
    title: 'Write changelog for v1.0',
    status: 'TODO',
    priority: 'MEDIUM',
    assigneeIndex: 1,
    sectionKey: 'engineering',
    dueInDays: 10,
  },
  {
    key: 'qa-invite-flow',
    title: 'QA invite-flow edge cases',
    status: 'TODO',
    priority: 'HIGH',
    assigneeIndex: 2,
    sectionKey: 'engineering',
    dueInDays: 5,
    startInDays: 0,
  },
  {
    key: 'rollback-runbook',
    title: 'Prepare rollback runbook',
    status: 'TODO',
    priority: 'HIGH',
    assigneeIndex: 'owner',
    sectionKey: 'launch-ops',
    dueInDays: 3,
    startInDays: -6,
  },
  {
    key: 'cs-checklist',
    title: 'Sync launch checklist with CS',
    status: 'TODO',
    priority: 'MEDIUM',
    assigneeIndex: 3,
    sectionKey: 'launch-ops',
    dueInDays: 8,
  },
  {
    key: 'swag-samples',
    title: 'Order branded swag samples',
    status: 'TODO',
    priority: 'NONE',
    assigneeIndex: null,
    sectionKey: 'gtm',
  },
  {
    key: 'linkedin-series',
    title: 'Draft LinkedIn post series',
    status: 'TODO',
    priority: 'LOW',
    assigneeIndex: 4,
    sectionKey: 'gtm',
    dueInDays: 18,
  },
  {
    key: 'feature-flags-ga',
    title: 'Configure feature flags for GA',
    status: 'TODO',
    priority: 'HIGH',
    assigneeIndex: 5,
    sectionKey: 'engineering',
    dueInDays: 5,
    startInDays: 0,
  },

  // —— IN_PROGRESS ——
  {
    key: 'keyboard-shortcuts',
    title: 'Ship board keyboard shortcuts',
    status: 'IN_PROGRESS',
    priority: 'HIGH',
    assigneeIndex: 0,
    sectionKey: 'engineering',
    dueInDays: 3,
    startInDays: -9,
  },
  {
    key: 'task-drawer',
    title: 'Polish task detail drawer',
    status: 'IN_PROGRESS',
    priority: 'MEDIUM',
    assigneeIndex: 1,
    sectionKey: 'engineering',
    dueInDays: 5,
    startInDays: -12,
  },
  {
    key: 'notif-badges',
    title: 'Implement notification badges',
    status: 'IN_PROGRESS',
    priority: 'HIGH',
    assigneeIndex: 2,
    sectionKey: 'engineering',
    dueInDays: 3,
    startInDays: -6,
  },
  {
    key: 'invite-loadtest',
    title: 'Load-test invite accept path',
    status: 'IN_PROGRESS',
    priority: 'MEDIUM',
    assigneeIndex: 3,
    sectionKey: 'engineering',
    dueInDays: 8,
    startInDays: -3,
  },
  {
    key: 'mobile-sidebar',
    title: 'Fix mobile sidebar collapse',
    status: 'IN_PROGRESS',
    priority: 'HIGH',
    assigneeIndex: 4,
    sectionKey: 'engineering',
    dueInDays: 0,
    startInDays: -15,
  },
  {
    key: 'empty-states',
    title: 'Add empty-state illustrations',
    status: 'IN_PROGRESS',
    priority: 'LOW',
    assigneeIndex: 5,
    sectionKey: 'design',
    dueInDays: 10,
    startInDays: -6,
  },
  {
    key: 'my-tasks-filters',
    title: 'Wire search filters for My Tasks',
    status: 'IN_PROGRESS',
    priority: 'HIGH',
    assigneeIndex: 'owner',
    sectionKey: 'engineering',
    dueInDays: 5,
    startInDays: -9,
  },
  {
    key: 'api-rate-limits',
    title: 'Document API rate limits',
    status: 'IN_PROGRESS',
    priority: 'MEDIUM',
    assigneeIndex: 0,
    sectionKey: 'engineering',
    dueInDays: 13,
    startInDays: -3,
  },
  {
    key: 'staging-seed',
    title: 'Migrate staging seed scripts',
    status: 'IN_PROGRESS',
    priority: 'MEDIUM',
    assigneeIndex: 1,
    sectionKey: 'engineering',
    dueInDays: 8,
    startInDays: -6,
  },
  {
    key: 'pg-indexes',
    title: 'Tune Postgres indexes for tasks',
    status: 'IN_PROGRESS',
    priority: 'HIGH',
    assigneeIndex: 2,
    sectionKey: 'engineering',
    dueInDays: 5,
    startInDays: -12,
  },
  {
    key: 'tour-video',
    title: 'Record product tour video',
    status: 'IN_PROGRESS',
    priority: 'MEDIUM',
    assigneeIndex: 3,
    sectionKey: 'gtm',
    dueInDays: 10,
    startInDays: -3,
  },
  {
    key: 'brand-tokens',
    title: 'Finalize brand color tokens',
    status: 'IN_PROGRESS',
    priority: 'LOW',
    assigneeIndex: 4,
    sectionKey: 'design',
    dueInDays: 15,
    startInDays: -9,
  },
  {
    key: 'partner-sso',
    title: 'Partner portal SSO spike',
    status: 'IN_PROGRESS',
    priority: 'MEDIUM',
    assigneeIndex: 5,
    sectionKey: 'engineering',
    dueInDays: 20,
    startInDays: -6,
  },
  {
    key: 'cs-playbook',
    title: 'Write customer success playbook',
    status: 'IN_PROGRESS',
    priority: 'MEDIUM',
    assigneeIndex: null,
    sectionKey: 'launch-ops',
    dueInDays: 18,
    startInDays: 0,
  },
  {
    key: 'beta-calls',
    title: 'Coordinate beta feedback calls',
    status: 'IN_PROGRESS',
    priority: 'HIGH',
    assigneeIndex: 'owner',
    sectionKey: 'launch-ops',
    dueInDays: 3,
    startInDays: -18,
  },

  // —— DONE / Foundation ——
  {
    key: 'theme-choice',
    title: 'Choose green/charcoal theme',
    status: 'DONE',
    priority: 'MEDIUM',
    assigneeIndex: 'owner',
    sectionKey: 'foundation',
    dueInDays: -30,
    startInDays: -42,
  },
  {
    key: 'scaffold-api',
    title: 'Scaffold NestJS + Prisma API',
    status: 'DONE',
    priority: 'HIGH',
    assigneeIndex: 0,
    sectionKey: 'foundation',
    dueInDays: -42,
    startInDays: -60,
  },
  {
    key: 'auth-ship',
    title: 'Ship email/password auth',
    status: 'DONE',
    priority: 'HIGH',
    assigneeIndex: 1,
    sectionKey: 'foundation',
    dueInDays: -36,
    startInDays: -48,
  },
  {
    key: 'invite-mock',
    title: 'Workspace invite mock flow',
    status: 'DONE',
    priority: 'HIGH',
    assigneeIndex: 2,
    sectionKey: 'foundation',
    dueInDays: -27,
    startInDays: -39,
  },
  {
    key: 'kanban-mvp',
    title: 'Kanban board MVP',
    status: 'DONE',
    priority: 'HIGH',
    assigneeIndex: 3,
    sectionKey: 'foundation',
    dueInDays: -24,
    startInDays: -36,
  },
  {
    key: 'comments-activity',
    title: 'Task comments + activity',
    status: 'DONE',
    priority: 'MEDIUM',
    assigneeIndex: 4,
    sectionKey: 'foundation',
    dueInDays: -21,
    startInDays: -33,
  },
  {
    key: 'member-table',
    title: 'Role-based member table',
    status: 'DONE',
    priority: 'MEDIUM',
    assigneeIndex: 5,
    sectionKey: 'foundation',
    dueInDays: -18,
    startInDays: -30,
  },
  {
    key: 'docker-pg',
    title: 'Docker Compose Postgres setup',
    status: 'DONE',
    priority: 'LOW',
    assigneeIndex: 'owner',
    sectionKey: 'foundation',
    dueInDays: -45,
    startInDays: -54,
  },
  {
    key: 'shared-package',
    title: 'Shared status/role package',
    status: 'DONE',
    priority: 'LOW',
    assigneeIndex: 0,
    sectionKey: 'foundation',
    dueInDays: -39,
    startInDays: -51,
  },
  {
    key: 'auth-screens',
    title: 'Login / register screens',
    status: 'DONE',
    priority: 'MEDIUM',
    assigneeIndex: 1,
    sectionKey: 'foundation',
    dueInDays: -33,
    startInDays: -45,
  },
  {
    key: 'project-list',
    title: 'Project list + create form',
    status: 'DONE',
    priority: 'MEDIUM',
    assigneeIndex: 2,
    sectionKey: 'foundation',
    dueInDays: -30,
    startInDays: -42,
  },
  {
    key: 'assignee-dropdown',
    title: 'Task assignee dropdown',
    status: 'DONE',
    priority: 'HIGH',
    assigneeIndex: 3,
    sectionKey: 'foundation',
    dueInDays: -15,
    startInDays: -27,
  },
  {
    key: 'priority-field',
    title: 'Priority field on tasks',
    status: 'DONE',
    priority: 'MEDIUM',
    assigneeIndex: 4,
    sectionKey: 'foundation',
    dueInDays: -12,
    startInDays: -24,
  },
  {
    key: 'due-date-picker',
    title: 'Due date picker',
    status: 'DONE',
    priority: 'MEDIUM',
    assigneeIndex: 5,
    sectionKey: 'foundation',
    dueInDays: -9,
    startInDays: -21,
  },
  {
    key: 'favicon',
    title: 'Favicon + brand mark',
    status: 'DONE',
    priority: 'NONE',
    assigneeIndex: null,
    sectionKey: 'foundation',
    dueInDays: -6,
    startInDays: -15,
  },
  {
    key: 'seed-workmates',
    title: 'Seed workmate accounts',
    status: 'DONE',
    priority: 'LOW',
    assigneeIndex: 'owner',
    sectionKey: 'foundation',
    dueInDays: -3,
    startInDays: -9,
  },

  // —— Subtasks ——
  {
    key: 'announce-copy-headline',
    title: 'Lock announcement headline options',
    status: 'TODO',
    priority: 'HIGH',
    assigneeIndex: 0,
    sectionKey: 'gtm',
    parentKey: 'announce-copy',
    dueInDays: 3,
  },
  {
    key: 'announce-copy-cta',
    title: 'Draft CTA + social snippets',
    status: 'TODO',
    priority: 'MEDIUM',
    assigneeIndex: 2,
    sectionKey: 'gtm',
    parentKey: 'announce-copy',
    dueInDays: 5,
  },
  {
    key: 'keyboard-nav',
    title: 'Arrow-key column navigation',
    status: 'IN_PROGRESS',
    priority: 'HIGH',
    assigneeIndex: 0,
    sectionKey: 'engineering',
    parentKey: 'keyboard-shortcuts',
    dueInDays: 3,
    startInDays: -6,
  },
  {
    key: 'keyboard-hotkeys',
    title: 'Hotkeys for create / complete task',
    status: 'TODO',
    priority: 'MEDIUM',
    assigneeIndex: 0,
    sectionKey: 'engineering',
    parentKey: 'keyboard-shortcuts',
    dueInDays: 3,
  },
  {
    key: 'drawer-fields',
    title: 'Custom fields panel polish',
    status: 'IN_PROGRESS',
    priority: 'MEDIUM',
    assigneeIndex: 1,
    sectionKey: 'engineering',
    parentKey: 'task-drawer',
    dueInDays: 5,
    startInDays: -3,
  },
  {
    key: 'drawer-deps',
    title: 'Dependencies UI in drawer',
    status: 'TODO',
    priority: 'HIGH',
    assigneeIndex: 1,
    sectionKey: 'engineering',
    parentKey: 'task-drawer',
    dueInDays: 5,
  },
  {
    key: 'rollback-db',
    title: 'Document DB rollback steps',
    status: 'TODO',
    priority: 'HIGH',
    assigneeIndex: 'owner',
    sectionKey: 'launch-ops',
    parentKey: 'rollback-runbook',
    dueInDays: 3,
  },
  {
    key: 'rollback-flags',
    title: 'List feature flags to disable first',
    status: 'IN_PROGRESS',
    priority: 'HIGH',
    assigneeIndex: 5,
    sectionKey: 'launch-ops',
    parentKey: 'rollback-runbook',
    dueInDays: 0,
    startInDays: -3,
  },
  {
    key: 'beta-schedule',
    title: 'Schedule remaining beta interviews',
    status: 'IN_PROGRESS',
    priority: 'HIGH',
    assigneeIndex: 'owner',
    sectionKey: 'launch-ops',
    parentKey: 'beta-calls',
    dueInDays: 3,
    startInDays: -9,
  },
  {
    key: 'beta-notes',
    title: 'Synthesize feedback themes',
    status: 'TODO',
    priority: 'MEDIUM',
    assigneeIndex: 4,
    sectionKey: 'launch-ops',
    parentKey: 'beta-calls',
    dueInDays: 8,
  },
]
